# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnostics-widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_widget_diagnostics(QtGui.QWidget):
    def setupUi(self, widget_diagnostics):
        widget_diagnostics.setObjectName(_fromUtf8("widget_diagnostics"))
        widget_diagnostics.resize(350, 770)
        widget_diagnostics.setMaximumSize(QtCore.QSize(370, 770))
        widget_diagnostics.setLayoutDirection(QtCore.Qt.LeftToRight)
        widget_diagnostics.setStyleSheet(_fromUtf8("font: 75 10pt \"Segoe UI Semibold\";"))
        self.groupBox_battery = QtGui.QGroupBox(widget_diagnostics)
        self.groupBox_battery.setGeometry(QtCore.QRect(8, 89, 331, 111))
        self.groupBox_battery.setFlat(False)
        self.groupBox_battery.setCheckable(False)
        self.groupBox_battery.setObjectName(_fromUtf8("groupBox_battery"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_battery)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 101, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_batteryIcon = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_batteryIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.label_batteryIcon.setText(_fromUtf8(""))
        self.label_batteryIcon.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/battery.png")))
        self.label_batteryIcon.setScaledContents(True)
        self.label_batteryIcon.setObjectName(_fromUtf8("label_batteryIcon"))
        self.verticalLayout.addWidget(self.label_batteryIcon)
        self.label_batteryVal = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_batteryVal.setObjectName(_fromUtf8("label_batteryVal"))
        self.verticalLayout.addWidget(self.label_batteryVal)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_battery)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 30, 121, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_busVolt = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_busVolt.setObjectName(_fromUtf8("label_busVolt"))
        self.verticalLayout_2.addWidget(self.label_busVolt)
        self.label_busVoltVal = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_busVoltVal.setObjectName(_fromUtf8("label_busVoltVal"))
        self.verticalLayout_2.addWidget(self.label_busVoltVal)
        self.groupBox_attitude = QtGui.QGroupBox(widget_diagnostics)
        self.groupBox_attitude.setGeometry(QtCore.QRect(10, 220, 331, 121))
        self.groupBox_attitude.setObjectName(_fromUtf8("groupBox_attitude"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox_attitude)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 311, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_roll = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_roll.setObjectName(_fromUtf8("label_roll"))
        self.horizontalLayout_2.addWidget(self.label_roll)
        self.label_pitch = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_pitch.setObjectName(_fromUtf8("label_pitch"))
        self.horizontalLayout_2.addWidget(self.label_pitch)
        self.label_yaw = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_yaw.setObjectName(_fromUtf8("label_yaw"))
        self.horizontalLayout_2.addWidget(self.label_yaw)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox_attitude)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 311, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_rollVal = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_rollVal.setObjectName(_fromUtf8("label_rollVal"))
        self.horizontalLayout_3.addWidget(self.label_rollVal)
        self.label_pitchVal = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_pitchVal.setObjectName(_fromUtf8("label_pitchVal"))
        self.horizontalLayout_3.addWidget(self.label_pitchVal)
        self.label_yawVal = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label_yawVal.setObjectName(_fromUtf8("label_yawVal"))
        self.horizontalLayout_3.addWidget(self.label_yawVal)
        self.groupBox = QtGui.QGroupBox(widget_diagnostics)
        self.groupBox.setGeometry(QtCore.QRect(10, 360, 331, 181))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 117, 41))
        self.verticalLayoutWidget_6.setObjectName(_fromUtf8("verticalLayoutWidget_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_arm = QtGui.QLabel(self.verticalLayoutWidget_6)
        self.label_arm.setObjectName(_fromUtf8("label_arm"))
        self.verticalLayout_6.addWidget(self.label_arm)
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 73, 241, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_12 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_12.setMaximumSize(QtCore.QSize(32, 32))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/propeller.png")))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_13.setMaximumSize(QtCore.QSize(32, 32))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/propeller.png")))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout.addWidget(self.label_13)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setMaximumSize(QtCore.QSize(32, 32))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/propeller.png")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_11.setMaximumSize(QtCore.QSize(32, 32))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/propeller.png")))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout.addWidget(self.label_11)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 130, 241, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_motor1Val = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_motor1Val.setObjectName(_fromUtf8("label_motor1Val"))
        self.horizontalLayout_4.addWidget(self.label_motor1Val)
        self.label_motor2Val = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_motor2Val.setObjectName(_fromUtf8("label_motor2Val"))
        self.horizontalLayout_4.addWidget(self.label_motor2Val)
        self.label_motor3Val = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_motor3Val.setObjectName(_fromUtf8("label_motor3Val"))
        self.horizontalLayout_4.addWidget(self.label_motor3Val)
        self.label_motor4Val = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_motor4Val.setObjectName(_fromUtf8("label_motor4Val"))
        self.horizontalLayout_4.addWidget(self.label_motor4Val)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(130, 20, 131, 41))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_ch1armVal = QtGui.QLabel(self.horizontalLayoutWidget_6)
        self.label_ch1armVal.setObjectName(_fromUtf8("label_ch1armVal"))
        self.horizontalLayout_6.addWidget(self.label_ch1armVal)
        self.groupBox_2 = QtGui.QGroupBox(widget_diagnostics)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 560, 331, 181))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 311, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_IMUcal = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_IMUcal.setObjectName(_fromUtf8("label_IMUcal"))
        self.horizontalLayout_5.addWidget(self.label_IMUcal)
        self.label_IMUcalVal = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.label_IMUcalVal.setObjectName(_fromUtf8("label_IMUcalVal"))
        self.horizontalLayout_5.addWidget(self.label_IMUcalVal)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 70, 311, 41))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_mode = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_mode.setObjectName(_fromUtf8("label_mode"))
        self.horizontalLayout_7.addWidget(self.label_mode)
        self.label_modeVal = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_modeVal.setObjectName(_fromUtf8("label_modeVal"))
        self.horizontalLayout_7.addWidget(self.label_modeVal)
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 120, 311, 41))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_autoMode = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_autoMode.setObjectName(_fromUtf8("label_autoMode"))
        self.horizontalLayout_8.addWidget(self.label_autoMode)
        self.label_autoModeVal = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_autoModeVal.setObjectName(_fromUtf8("label_autoModeVal"))
        self.horizontalLayout_8.addWidget(self.label_autoModeVal)
        self.label = QtGui.QLabel(widget_diagnostics)
        self.label.setGeometry(QtCore.QRect(120, 20, 91, 61))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../assets/bakkup-logo.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(widget_diagnostics)
        QtCore.QMetaObject.connectSlotsByName(widget_diagnostics)

    def retranslateUi(self, widget_diagnostics):
        widget_diagnostics.setWindowTitle(_translate("widget_diagnostics", "First Flight Drone - Diagnostics", None))
        self.groupBox_battery.setTitle(_translate("widget_diagnostics", "Battery", None))
        self.label_batteryVal.setText(_translate("widget_diagnostics", "TBD%", None))
        self.label_busVolt.setText(_translate("widget_diagnostics", "Bus Voltage", None))
        self.label_busVoltVal.setText(_translate("widget_diagnostics", "TBD V", None))
        self.groupBox_attitude.setTitle(_translate("widget_diagnostics", "Attitude (m/sec^2)", None))
        self.label_roll.setText(_translate("widget_diagnostics", "X-accel", None))
        self.label_pitch.setText(_translate("widget_diagnostics", "Y-accel", None))
        self.label_yaw.setText(_translate("widget_diagnostics", "Z-accel", None))
        self.label_rollVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.label_pitchVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.label_yawVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.groupBox.setTitle(_translate("widget_diagnostics", "Motor", None))
        self.label_arm.setText(_translate("widget_diagnostics", "Armed/Disarmed", None))
        self.label_12.setToolTip(_translate("widget_diagnostics", "<html><head/><body><p>Motor 1</p></body></html>", None))
        self.label_13.setToolTip(_translate("widget_diagnostics", "<html><head/><body><p>Motor 2</p></body></html>", None))
        self.label_10.setToolTip(_translate("widget_diagnostics", "<html><head/><body><p>Motor 3</p></body></html>", None))
        self.label_11.setToolTip(_translate("widget_diagnostics", "<html><head/><body><p>Motor 4</p></body></html>", None))
        self.label_motor1Val.setText(_translate("widget_diagnostics", "TBD%", None))
        self.label_motor2Val.setText(_translate("widget_diagnostics", "TBD%", None))
        self.label_motor3Val.setText(_translate("widget_diagnostics", "TBD%", None))
        self.label_motor4Val.setText(_translate("widget_diagnostics", "TBD%", None))
        self.label_ch1armVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.groupBox_2.setTitle(_translate("widget_diagnostics", "Drone Configurations", None))
        self.label_IMUcal.setText(_translate("widget_diagnostics", "IMU Calibration:", None))
        self.label_IMUcalVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.label_mode.setText(_translate("widget_diagnostics", "Manual/Autonomous:", None))
        self.label_modeVal.setText(_translate("widget_diagnostics", "TBD", None))
        self.label_autoMode.setText(_translate("widget_diagnostics", "Autonomous Mode:", None))
        self.label_autoModeVal.setText(_translate("widget_diagnostics", "TBD", None))
